In [1]:
import requests
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
import time

driver=webdriver.Chrome(executable_path="D:\esmes8\projet-expat\chromedriver.exe")
print(type(driver))

C:\Users\barra\AppData\Local\Temp\ipykernel_31596\3246519785.py:8: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(executable_path="D:\esmes8\projet-expat\chromedriver.exe")

<class 'selenium.webdriver.chrome.webdriver.WebDriver'>

In [2]:
df_world_happiness_report = pd.read_csv('world-happiness-report-2021.csv',sep=';')
df_world_happiness_report

,Country_Name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.000,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.700,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.400,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.000,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.400,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Lesotho,Sub-Saharan Africa,3.512,0.120,3.748,3.276,7.926,0.787,48.700,0.715,-0.131,0.915,2.43,0.451,0.731,0.007,0.405,0.103,0.015,1.800
145,Botswana,Sub-Saharan Africa,3.467,0.074,3.611,3.322,9.782,0.784,59.269,0.824,-0.246,0.801,2.43,1.099,0.724,0.340,0.539,0.027,0.088,0.648
146,Rwanda,Sub-Saharan Africa,3.415,0.068,3.548,3.282,7.676,0.552,61.400,0.897,0.061,0.167,2.43,0.364,0.202,0.407,0.627,0.227,0.493,1.095
147,Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.030,7.943,0.750,56.201,0.677,-0.047,0.821,2.43,0.457,0.649,0.243,0.359,0.157,0.075,1.205
148,Afghanistan,South Asia,2.523,0.038,2.596,2.449,7.695,0.463,52.493,0.382,-0.102,0.924,2.43,0.370,0.000,0.126,0.000,0.122,0.010,1.895

In [3]:
L_pays_taux=[]
pays_taux=[]
def get_tx_chom_from_country(pays_taux):
    '''
        Get taux chomage info par pays

        :param pays_taux: liste de pays
        :type pays_taux: liste de String
        :return: 
                - noms_pays: liste de pays
                - taux_chom: liste des taux correspondants
        :rtype: tuple(string, string)
    '''
    
    url = 'https://fr.countryeconomy.com/marche-du-travail/chomage'
    driver.get(url)
    
    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'html.parser')

    table_pays_tx_chom = soup.find('table', class_ = 'table tabledat table-striped table-condensed table-hover')
    L=[]
    for pays in table_pays_tx_chom.find_all('tbody'):
        lignes = pays.find_all('tr')
        nom_pays=[]
        taux_chom=[]
        for ligne in lignes: 
            noms_pays = ligne.find('td').text.strip('[+]')
            taux_chom = ligne.find('td', class_ = 'numero').text.strip('%')
            L.append(noms_pays)
            nom_pays.append(noms_pays)
            taux_chom.append(taux_chom)
        return nom_pays,taux_chom

tous fonctione trés bien sauf que la langue source est le francais or nos autre datase sont en anglais, donc on la traduit par reverso et on garde donc cette version la pour pouvoir avoir une clé commune au moment du merge

In [4]:

# L1,L2 = get_tx_chom_from_country(L_pays_taux)
# data = {'nom pays':L1,'taux de chomage en %':L2}
# taux_chom_pays=pd.DataFrame(data)
# taux_chom_pays
# taux_chom_pays.to_csv(sep=';',path_or_buf='name_to_translate.csv',index=False,index_label=False,encoding='latin',decimal=',')

In [4]:
taux_chom_pays=pd.read_csv('name_translate.csv',sep=';')
taux_chom_pays

       Country_Name unemployment rate in %
0           France                     7,4
1          Germany                     2,9
2        Euro zone                     7,6
3   United Kingdom                     3,8
4            Spain                    13,5
5    United States                     3,6
6            Japon                     2,6
7           Italie                     8,3
8         Portugal                     5,7
9           Greece                    12,9
10         Irlande                     4,8
11       Argentina                     8,5
12         Austria                     4,2
13       Australie                     4,0
14         Belgium                     5,6
15        Bulgarie                     4,3
16          Brésil                    13,2
17          Canada                     5,2
18     Switzerland                     4,5
19           Chili                     7,8
20        Colombie                    11,0
21          Chypre                     5,9
22        Tchéquie                     2,3
23        Danemark                     4,5
24         Estonie                     5,4
25        Finlande                     6,4
26         Croatie                     6,5
27         Hongrie                     3,2
28         Islande                     4,3
29        Lituanie                     6,9
30      Luxembourg                     4,5
31        Lettonie                     7,0
32           Malte                     3,0
33          Mexico                     3,0
34     Netherlands                     3,3
35         Norvège                     3,1
36          Poland                     3,0
37         Romania                     5,7
38          Russie                     4,3
39           Suède                     7,6
40        Slovénie                     4,0
41        Slovakia                     6,5
42         Turquie                    11,2
43         Uruguay                     9,4
44       Venezuela                     6,4
45    South Africa                    35,3

In [5]:
country_col_index=[]
L_country_col_index=[]
def get_cost_of_living_index_by_country(country_col_index):
    '''
        Get cost-of-living index info par pays

        :param country_col_index: liste de pays
        :type country_col_index: liste de String
        :return: 
                - country_name: liste de pays
                - col_index: Taux du coût-de-vie
                - rent_index: Taux Loyer
                - col_plus_rent_index: Taux coût-de-vie + Loyer
                - groceries_index: indice courses
                - rp_index: indice de prix des restaurants
                - lpp_index: indice de pouvoir d'achat local
        :rtype: tuple(string, float, float, float, float, float, float)
    '''
    
    url = 'https://www.numbeo.com/cost-of-living/rankings_by_country.jsp'
    driver.get(url)
    
    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'html.parser')

    table_col = soup.find('table', id = 't2')

    for country in table_col.find_all('tbody'):
        rows = country.find_all('tr')
        country_nam = []
        col_inde= []
        rent_inde= []
        col_plus_rent_inde= []
        groceries_inde= []
        rp_inde= []
        lpp_inde= []

        for row in rows: 
            country_name = row.find('td', class_ = 'cityOrCountryInIndicesTable').text.strip() #nom pays
            col_index = row.find_all('td')[2].text #indice de cout de vie 
            rent_index = row.find_all('td')[3].text #indice des loyers
            col_plus_rent_index = row.find_all('td')[4].text #indice cout de vie + loyers
            groceries_index = row.find_all('td')[5].text #indice courses
            rp_index = row.find_all('td')[6].text #indice prix restaurant
            lpp_index = row.find_all('td')[7].text #indice de pouvoir d'achat local
            country_nam.append(country_name)
            col_inde.append(col_index)
            rent_inde.append(rent_inde)
            col_plus_rent_inde.append(col_plus_rent_index)
            groceries_inde.append(groceries_index)
            rp_inde.append(rp_index)
            lpp_inde.append(lpp_index)

        return country_nam,col_inde,rent_inde,col_plus_rent_inde,groceries_inde,rp_inde,lpp_inde

#test

In [6]:
country_nam,col_inde,rent_inde,col_plus_rent_inde,groceries_inde,rp_inde,lpp_inde=get_cost_of_living_index_by_country(L_country_col_index)
data = {'Country_Name':country_nam,'cost of living index':col_inde,'cost of living plus rent index':col_plus_rent_inde,'Groceries index':groceries_inde,'restaurant price index':rp_inde,'local purchasing power index':lpp_inde}
cost_of_living_index = pd.DataFrame(data)
cost_of_living_index

,Country_Name,cost of living index,cost of living plus rent index,Groceries index,restaurant price index,local purchasing power index
0,Bermuda,146.04,123.80,148.66,159.17,81.07
1,Switzerland,123.35,90.62,128.13,122.09,118.44
2,Norway,100.90,69.86,97.31,105.49,83.11
3,Iceland,94.86,70.05,90.22,99.42,77.06
4,Barbados,92.37,59.38,87.81,78.18,32.08
...,...,...,...,...,...,...
134,Algeria,26.87,16.43,28.82,14.48,24.63
135,Colombia,26.72,18.03,23.47,19.44,28.85
136,India,24.43,15.47,26.43,17.56,49.72
137,Afghanistan,20.37,12.09,14.92,12.41,23.04
138,Pakistan,19.92,12.42,17.81,15.54,26.63

In [10]:
list_vfc=[]
pays_vfc=[]
def get_visa_free_country_for_french(pays_vfc):
    '''
        Get pays où un français n'a pas besoin de visa pour entrer

        :param pays_vfc: liste de pays
        :type pays_vfc: liste de String
        :return: 
                - noms_pays: liste de pays 1/2
                - allowed_stay: durées maximales authorisées 1/2
                - noms_pays2: liste de pays 2/2
                - allowed_stay2: durées maximales authorisées 2/2
        :rtype: tuple(string, string, string, string)
    '''
    
    url = 'https://visaguide.world/visa-free-countries/french-passport/'
    driver.get(url)
    
    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'html.parser')

    table_pays_visa_free = soup.find('table', class_ = 'tablepress tablepress-id-71')

    for pays in table_pays_visa_free.find_all('tbody'):
        lignes = pays.find_all('tr')
        nom=[]
        stay=[]
        for ligne in lignes: 
            noms_pays = ligne.find('td', class_ = 'column-1').text.strip()
            allowed_stay = ligne.find('td', class_ = 'column-2').text.strip()
            noms_pays2 = ligne.find('td', class_ = 'column-3').text.strip()
            allowed_stay2 = ligne.find('td', class_ = 'column-4').text.strip()
            list_vfc.append(noms_pays)
            list_vfc.append(noms_pays2)
            nom.append(noms_pays)
            nom.append(noms_pays2)
            # nom2.append(noms_pays2)
            stay.append(allowed_stay)
            stay.append(allowed_stay2)
            # stay2.append(allowed_stay2)
            # print(noms_pays, allowed_stay)
            # print (noms_pays2, allowed_stay2)b
        return nom,stay

In [11]:
noms_pays,allowed_stay = get_visa_free_country_for_french(list_vfc)
data = {'Country_Name':noms_pays,'time_available_on_site':allowed_stay,'required visa for french citizen':'not required'}
df_visa_free_country_for_french=pd.DataFrame(data)
df_visa_free_country_for_french

,Country_Name,time_available_on_site,required visa for french citizen
0,Albania,90 days,not required
1,Malta,Unlimited stay,not required
2,Andorra,90 days,not required
3,Marshall Islands,90 days,not required
4,Antigua and Barbuda,180 days,not required
...,...,...,...
117,Vatican City,1 day,not required
118,Macau,90 days,not required
119,Venezuela,90 days,not required
120,Malaysia,90 days,not required
121,Vietnam,15 days,not required

In [8]:
list_evisa=[]
pays_evisa=[]
def get_evisa_country_for_french(pays_evisa):
    '''
        Get pays où un français a besoin d'un evisa pour entrer

        :param pays_evisa: liste de pays
        :type pays_evisa: liste de String
        :return: 
                - noms_pays: liste de pays 
                - allowed_stay: durées maximales authorisées 
        :rtype: tuple(string, string)
    '''
    
    url = 'https://visaguide.world/visa-free-countries/french-passport/'
    driver.get(url)
    
    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'html.parser')
    
    
    table_pays_evisa_required = soup.find('table', class_ = 'tablepress tablepress-id-72')

    for pays in table_pays_evisa_required.find_all('tbody'):
        lignes = pays.find_all('tr')
        nom=[]
        stay=[]
        for ligne in lignes: 
            noms_pays = ligne.find('td', class_ = 'column-1').text.strip()
            allowed_stay = ligne.find('td', class_ = 'column-2').text.strip()
            list_evisa.append(noms_pays)
            nom.append(noms_pays)
            stay.append(allowed_stay)
            # print(noms_pays, allowed_stay)
        return nom,stay

In [9]:
noms_pays,allowed_stay = get_evisa_country_for_french(list_evisa)
data = {'Country_Name':noms_pays,'time_available_on_site':allowed_stay,'required visa for french citizen':'Evisa'}
df_evisa_country_for_french=pd.DataFrame(data)
df_evisa_country_for_french

,Country_Name,time_available_on_site,required visa for french citizen
0,Angola,30 days,Evisa
1,Australia,90 days,Evisa
2,Azerbaijan,30 days,Evisa
3,Bahrain,14 days,Evisa
4,Benin,30 days / 8 days,Evisa
5,Cambodia,30 days,Evisa
6,Democratic Republic of the Congo,3 months,Evisa
7,Cote d'Ivoire,3 months,Evisa
8,Djibouti,31 days,Evisa
9,Egypt,30 days,Evisa
10,Ethiopia,up to 90 days,Evisa
11,Gabon,90 days,Evisa
12,Guinea,90 days,Evisa
13,Guinea-Bissau,90 days,Evisa
14,India,60 days,Evisa
15,Iran,30 days,Evisa
16,Kenya,3 months,Evisa
17,Kuwait,3 months,Evisa
18,Laos,30 days,Evisa
19,Madagascar,90 days,Evisa
20,Malawi,90 days,Evisa
21,Myanmar,28 days,Evisa
22,New Zealand,3 months,Evisa
23,Nigeria,90 days,Evisa
24,Pakistan,3 months,Evisa
25,Papua New Guinea,60 days,Evisa
26,Russia,16 days,Evisa
27,Rwanda,30 days,Evisa
28,Saudi Arabia,90 days,Evisa
29,South Sudan,3 months up to 6,Evisa
30,Sri Lanka,30 days,Evisa
31,Suriname,90 days,Evisa
32,Tanzania,3 months,Evisa
33,Uganda,90 days,Evisa
34,Zambia,90 days,Evisa
35,Zimbabwe,3 months,Evisa

In [12]:
list_visa_oa=[]
pays_visa_oa=[]
def get_visa_on_arrival_country_for_french(pays_visa_oa):
    '''
        Get pays où un français a besoin d'un visa à son arrivée

        :param pays_visa_oa: liste de pays
        :type pays_visa_oa: liste de String
        :return: 
                - noms_pays: liste de pays 
                - allowed_stay: durées maximales authorisées 
        :rtype: tuple(string, string)
    '''
    
    url = 'https://visaguide.world/visa-free-countries/french-passport/'
    driver.get(url)
    
    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'html.parser')
    
    
    table_pays_visa_on_arrival_requirements = soup.find('table', class_ = 'tablepress tablepress-id-73')

    for pays in table_pays_visa_on_arrival_requirements.find_all('tbody'):
        lignes = pays.find_all('tr')
        nom=[]
        stay=[]
        for ligne in lignes: 
            noms_pays = ligne.find('td', class_ = 'column-1').text.strip()
            allowed_stay = ligne.find('td', class_ = 'column-2').text.strip()
            list_visa_oa.append(noms_pays)
            nom.append(noms_pays)
            stay.append(allowed_stay)
            # print(noms_pays, allowed_stay)
        return nom,stay

In [13]:
noms_pays,allowed_stay = get_visa_on_arrival_country_for_french(list_visa_oa)
allowed_stay = [a.replace('(renewable)','renewable')for a in allowed_stay]
allowed_stay = [a.replace('(with extension)','with extension')for a in allowed_stay]
data = {'Country_Name':noms_pays,'time_available_on_site':allowed_stay,'required visa for french citizen':'required to stay'}
df_visa_on_arrival_country_for_french=pd.DataFrame(data)

In [14]:
df_visa_on_arrival_country_for_french

        Country_Name  time_available_on_site required visa for french citizen
0            Bahrain                 14 days                 required to stay
1         Bangladesh                 30 days                 required to stay
2              Benin        30 days / 8 days                 required to stay
3       Burkina Faso                 1 month                 required to stay
4           Cambodia                 30 days                 required to stay
5            Comoros                 45 days                 required to stay
6              Egypt                 30 days                 required to stay
7           Ethiopia           up to 90 days                 required to stay
8              Gabon                 90 days                 required to stay
9             Gambia       15 days renewable                 required to stay
10     Guinea-Bissau                 90 days                 required to stay
11              Iraq                 60 days                 required to stay
12            Jordan                 1 month                 required to stay
13             Kenya                3 months                 required to stay
14            Kuwait                3 months                 required to stay
15              Laos                 30 days                 required to stay
16           Lebanon                 1 month                 required to stay
17        Madagascar                 90 days                 required to stay
18            Malawi                 90 days                 required to stay
19          Maldives                 30 days                 required to stay
20        Mauritania         1 month up to 2                 required to stay
21        Mozambique                 30 days                 required to stay
22             Nepal                 90 days                 required to stay
23          Pakistan                3 months                 required to stay
24  Papua New Guinea                 60 days                 required to stay
25            Rwanda                 30 days                 required to stay
26      Saudi Arabia                 90 days                 required to stay
27      Sierra Leone  1 month with extension                 required to stay
28           Somalia                 1 month                 required to stay
29         Sri Lanka                 30 days                 required to stay
30        Tajikistan                 45 days                 required to stay
31          Tanzania                3 months                 required to stay
32              Togo                  7 days                 required to stay
33            Uganda                 90 days                 required to stay
34            Zambia                 90 days                 required to stay
35          Zimbabwe                3 months                 required to stay

In [17]:
list_visa_required=[]
pays_visa_required=[]
def get_visa_requirement_country_for_french(pays_visa_required):
    '''
        Get pays où un français a besoin d'un visa pour entrer dans le pays

        :param pays_visa_required: liste de pays
        :type pays_visa_required: liste de String
        :return: 
                - noms_pays: liste de pays 1/3 
                - noms_pays2: liste de pays 2/3
                - noms_pays3: liste de pays 3/3
        :rtype: tuple(string, string, string)
    '''
    
    url = 'https://visaguide.world/visa-free-countries/french-passport/'
    driver.get(url)
    
    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'html.parser')
    
    
    table_pays_visa_requirement_to_enter = soup.find('table', class_ = 'tablepress tablepress-id-74')

    for pays in table_pays_visa_requirement_to_enter.find_all('tbody'):
        lignes = pays.find_all('tr')
        for ligne in lignes: 
            noms_pays = ligne.find('td', class_ = 'column-1').text.strip()
            noms_pays2 = ligne.find('td', class_ = 'column-2').text.strip()
            noms_pays3 = ligne.find('td', class_ = 'column-3').text.strip()
            list_visa_required.append(noms_pays)
            list_visa_required.append(noms_pays2)
            list_visa_required.append(noms_pays3)
            # print(noms_pays)
            # print(noms_pays2)
            # print(noms_pays3)
        return list_visa_required

In [19]:
get_visa_requirement_country_for_french(list_visa_oa)

['Afghanistan',
 'China',
 'Mali',
 'Algeria',
 'Republic of the Congo',
 'Mongolia',
 'Belarus',
 'Equatorial Guinea',
 'Nauru',
 'Bhutan',
 'Eritrea',
 'Niger',
 'Burundi',
 'Ghana',
 'Sudan',
 'Cameroon',
 'North Korea',
 'Syria',
 'Central African Republic',
 'Liberia',
 'Turkmenistan',
 'Chad',
 'Libya',
 'Yemen']

In [20]:
noms_pays= get_visa_requirement_country_for_french(list_visa_oa)
data = {'Country_Name':noms_pays,'time_available_on_site':'/','required visa for french citizen':'particular country information on embassy site'}
df_visa_requirement_country_for_french=pd.DataFrame(data)
df_visa_requirement_country_for_french

,Country_Name,time_available_on_site,required visa for french citizen
0,Afghanistan,/,particular country information on embassy site
1,China,/,particular country information on embassy site
2,Mali,/,particular country information on embassy site
3,Algeria,/,particular country information on embassy site
4,Republic of the Congo,/,particular country information on embassy site
5,Mongolia,/,particular country information on embassy site
6,Belarus,/,particular country information on embassy site
7,Equatorial Guinea,/,particular country information on embassy site
8,Nauru,/,particular country information on embassy site
9,Bhutan,/,particular country information on embassy site
10,Eritrea,/,particular country information on embassy site
11,Niger,/,particular country information on embassy site
12,Burundi,/,particular country information on embassy site
13,Ghana,/,particular country information on embassy site
14,Sudan,/,particular country information on embassy site
15,Cameroon,/,particular country information on embassy site
16,North Korea,/,particular country information on embassy site
17,Syria,/,particular country information on embassy site
18,Central African Republic,/,particular country information on embassy site
19,Liberia,/,particular country information on embassy site
20,Turkmenistan,/,particular country information on embassy site
21,Chad,/,particular country information on embassy site
22,Libya,/,particular country information on embassy site
23,Yemen,/,particular country information on embassy site
24,Afghanistan,/,particular country information on embassy site
25,China,/,particular country information on embassy site
26,Mali,/,particular country information on embassy site
27,Algeria,/,particular country information on embassy site
28,Republic of the Congo,/,particular country information on embassy site
29,Mongolia,/,particular country information on embassy site
30,Belarus,/,particular country information on embassy site
31,Equatorial Guinea,/,particular country information on embassy site
32,Nauru,/,particular country information on embassy site
33,Bhutan,/,particular country information on embassy site
34,Eritrea,/,particular country information on embassy site
35,Niger,/,particular country information on embassy site
36,Burundi,/,particular country information on embassy site
37,Ghana,/,particular country information on embassy site
38,Sudan,/,particular country information on embassy site
39,Cameroon,/,particular country information on embassy site
40,North Korea,/,particular country information on embassy site
41,Syria,/,particular country information on embassy site
42,Central African Republic,/,particular country information on embassy site
43,Liberia,/,particular country information on embassy site
44,Turkmenistan,/,particular country information on embassy site
45,Chad,/,particular country information on embassy site
46,Libya,/,particular country information on embassy site
47,Yemen,/,particular country information on embassy site

In [ ]:
cost_of_living_index.shape

(139, 6)

In [35]:
#merge des 2 plus gros d'un coté
df_merge = df_world_happiness_report.merge(
    cost_of_living_index,how='inner',on='Country_Name'
)

df_merge_for_visa = pd.concat([df_evisa_country_for_french,df_visa_free_country_for_french,df_visa_on_arrival_country_for_french,df_visa_requirement_country_for_french])
df_merge_for_visa=df_merge_for_visa.drop_duplicates(keep='first',subset='Country_Name')

In [38]:
#et enfin on merge toute ces dataframe ensemble 

df_all = df_merge.merge(
    df_merge_for_visa,how='inner',on='Country_Name'
)
df_all

,Country_Name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,...,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,cost of living index,cost of living plus rent index,Groceries index,restaurant price index,local purchasing power index,time_available_on_site,required visa for french citizen
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.000,0.949,...,0.124,0.481,3.253,73.20,51.05,65.16,77.65,91.02,Unlimited stay,not required
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.700,0.946,...,0.208,0.485,2.868,84.12,60.26,68.60,98.75,99.45,Unlimited stay,not required
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.400,0.919,...,0.204,0.413,2.839,123.35,90.62,128.13,122.09,118.44,Unlimited stay,not required
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.000,0.955,...,0.293,0.170,2.967,94.86,70.05,90.22,99.42,77.06,Unlimited stay,not required
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.400,0.913,...,0.302,0.384,2.798,75.66,57.10,65.49,76.35,87.99,Unlimited stay,not required
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,Tanzania,Sub-Saharan Africa,3.623,0.071,3.762,3.485,7.876,0.702,57.999,0.833,...,0.307,0.231,1.263,32.81,23.23,30.04,24.86,15.97,3 months,Evisa
111,Botswana,Sub-Saharan Africa,3.467,0.074,3.611,3.322,9.782,0.784,59.269,0.824,...,0.027,0.088,0.648,40.17,26.12,35.16,42.50,62.63,90 days,not required
112,Rwanda,Sub-Saharan Africa,3.415,0.068,3.548,3.282,7.676,0.552,61.400,0.897,...,0.227,0.493,1.095,31.62,24.25,27.71,27.99,26.82,30 days,Evisa
113,Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.030,7.943,0.750,56.201,0.677,...,0.157,0.075,1.205,45.68,28.37,39.88,38.13,19.07,3 months,Evisa
114,Afghanistan,South Asia,2.523,0.038,2.596,2.449,7.695,0.463,52.493,0.382,...,0.122,0.010,1.895,20.37,12.09,14.92,12.41,23.04,/,particular country information on embassy site

In [ ]:
#Les googleapis sont utilisés sur des routes existantes mais il n'existe pas de mode de voyage par avion.
pays_ue=[]
List_pays_ue = ['Allemagne', 'Autriche', 'Belgique', 'Bulgarie', 'Croatie', 'Danemark', 'Espagne', 'Estonie', 'Finlande', 'Grèce', 'Hongrie', 'Irlande', 'Italie', 'Lettonie', 'Lituanie', 'Luxembourg', 'Malte', 'Pays-Bas', 'Pologne', 'Portugal', 'République-Tchèque', 'Roumanie', 'Slovaquie', 'Slovénie', 'Suède']
lenght=len(List_pays_ue)

In [ ]:
def get_distance_and_duration_from_france_to_eu_country(pays_ue):
    '''
        Get distance et durée qui sépare un français d'un autre pays

        :param pays_ue: liste de pays de l'union européene
        :type pays_ue: liste de String
        :return: 
                - output: dictionnaire contenant des données json de la page d'url=url_full
                - data['distance']: données distances en km
                - data['duration']: données durées en prenant la voiture en heures et minutes
        :rtype: dict
    '''

    for i in range(lenght):
    
        apikey = "AIzaSyCouNtR_wHK7g20CTnB5b6h6aMWdatk4q0"
        url1 = "https://maps.googleapis.com/maps/api/distancematrix/json?origins="
        origin = "France"
        url2 = "&destinations="
        destination = List_pays_ue[i]
        url3 = "&mode=car&key="

        url_full = url1+origin+url2+destination+url3+apikey
        output = requests.get(url_full).json()
        print(output)
        print(type(output))
        for obj in output['rows']:
            for data in obj['elements']:
                print(data['distance']['text'])
                print(data['duration']['text'])

In [ ]:
get_distance_and_duration_from_france_to_eu_country(List_pays_ue)

{'destination_addresses': ['Germany'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '1,035 km', 'value': 1034936}, 'duration': {'text': '11 hours 2 mins', 'value': 39690}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
1,035 km
11 hours 2 mins
{'destination_addresses': ['Austria'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '1,262 km', 'value': 1262203}, 'duration': {'text': '13 hours 26 mins', 'value': 48340}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
1,262 km
13 hours 26 mins
{'destination_addresses': ['Belgium'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '657 km', 'value': 656567}, 'duration': {'text': '6 hours 21 mins', 'value': 22887}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
657 km
6 hours 21 mins
{'destination_addresses': ['Bulgaria'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '2,435 km', 'value': 2435181}, 'duration': {'text': '1 day 1 hour', 'value': 90608}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
2,435 km
1 day 1 hour
{'destination_addresses': ['Croatia'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '1,347 km', 'value': 1346616}, 'duration': {'text': '14 hours 1 min', 'value': 50452}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
1,347 km
14 hours 1 min
{'destination_addresses': ['Denmark'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '1,607 km', 'value': 1607396}, 'duration': {'text': '15 hours 59 mins', 'value': 57558}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
1,607 km
15 hours 59 mins
{'destination_addresses': ['Spain'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '1,002 km', 'value': 1001972}, 'duration': {'text': '10 hours 16 mins', 'value': 36975}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
1,002 km
10 hours 16 mins
{'destination_addresses': ['Estonia'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '2,743 km', 'value': 2743281}, 'duration': {'text': '1 day 6 hours', 'value': 106493}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
2,743 km
1 day 6 hours
{'destination_addresses': ['Finland'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '3,149 km', 'value': 3148911}, 'duration': {'text': '1 day 13 hours', 'value': 132053}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
3,149 km
1 day 13 hours
{'destination_addresses': ['Greece'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '2,629 km', 'value': 2628807}, 'duration': {'text': '1 day 3 hours', 'value': 98048}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
2,629 km
1 day 3 hours
{'destination_addresses': ['Hungary'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '1,666 km', 'value': 1666055}, 'duration': {'text': '16 hours 53 mins', 'value': 60806}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
1,666 km
16 hours 53 mins
{'destination_addresses': ['Ireland'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '1,598 km', 'value': 1597553}, 'duration': {'text': '17 hours 57 mins', 'value': 64644}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
1,598 km
17 hours 57 mins
{'destination_addresses': ['Italy'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '1,297 km', 'value': 1296932}, 'duration': {'text': '13 hours 2 mins', 'value': 46946}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
1,297 km
13 hours 2 mins
{'destination_addresses': ['Latvia'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '2,530 km', 'value': 2530162}, 'duration': {'text': '1 day 3 hours', 'value': 97032}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
2,530 km
1 day 3 hours
{'destination_addresses': ['Lithuania'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '2,297 km', 'value': 2296743}, 'duration': {'text': '23 hours 45 mins', 'value': 85489}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
2,297 km
23 hours 45 mins
{'destination_addresses': ['Luxembourg'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '680 km', 'value': 680259}, 'duration': {'text': '7 hours 18 mins', 'value': 26294}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
680 km
7 hours 18 mins
{'destination_addresses': ['Malta'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '2,322 km', 'value': 2321946}, 'duration': {'text': '1 day 2 hours', 'value': 93794}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
2,322 km
1 day 2 hours
{'destination_addresses': ['Netherlands'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '853 km', 'value': 852939}, 'duration': {'text': '8 hours 25 mins', 'value': 30309}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
853 km
8 hours 25 mins
{'destination_addresses': ['Poland'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '1,712 km', 'value': 1711776}, 'duration': {'text': '17 hours 34 mins', 'value': 63259}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
1,712 km
17 hours 34 mins
{'destination_addresses': ['Portugal'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '1,340 km', 'value': 1340415}, 'duration': {'text': '13 hours 29 mins', 'value': 48546}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
1,340 km
13 hours 29 mins
{'destination_addresses': ['Czechia'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '1,316 km', 'value': 1316327}, 'duration': {'text': '13 hours 41 mins', 'value': 49286}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
1,316 km
13 hours 41 mins
{'destination_addresses': ['Romania'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '2,257 km', 'value': 2257322}, 'duration': {'text': '23 hours 5 mins', 'value': 83085}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
2,257 km
23 hours 5 mins
{'destination_addresses': ['Slovakia'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '1,720 km', 'value': 1720187}, 'duration': {'text': '17 hours 45 mins', 'value': 63926}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
1,720 km
17 hours 45 mins
{'destination_addresses': ['Slovenia'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '1,292 km', 'value': 1291876}, 'duration': {'text': '13 hours 0 mins', 'value': 46814}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
1,292 km
13 hours 0 mins
{'destination_addresses': ['Sweden'], 'origin_addresses': ['France'], 'rows': [{'elements': [{'distance': {'text': '2,358 km', 'value': 2357712}, 'duration': {'text': '1 day 1 hour', 'value': 90074}, 'status': 'OK'}]}], 'status': 'OK'}
<class 'dict'>
2,358 km
1 day 1 hour